controller_manager:
  ros__parameters:
    update_rate: 100  # Hz (this can be as fast or slower than the ESP32's loop rate)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["wbot_wheel_left_joint"]
    right_wheel_names: ["wbot_wheel_right_joint"]

    wheel_separation: 0.287 # Shortest distance between the left and right wheels
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: wbot_base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    position_feedback: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 2.5
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 6.2
    angular.z.min_acceleration: -6.2
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
